"""Format completed task results as artifacts a maintainer can act on.

The primary output is a GitHub-issue-ready markdown body. A maintainer can pipe
it into `gh issue create --body-file -` (see `scripts/file_issue.sh`).
"""
from __future__ import annotations

import re
from datetime import datetime, timezone

from .schemas import ResultStatus, TaskRecord

_BUG_TAG_RE = re.compile(r"\[bug\]", re.IGNORECASE)


def count_bug_findings(output: str) -> int:
    """Count `[bug]` tags emitted by `review`-kind tasks."""
    if not output:
        return 0
    return len(_BUG_TAG_RE.findall(output))


def _kind_label(kind: str) -> str:
    return {
        "annotate": "Type annotations",
        "review": "Code review",
        "test-gen": "Generated tests",
    }.get(kind, kind.capitalize() if kind else "Task")


def issue_title(rec: TaskRecord) -> str:
    md = rec.task.metadata or {}
    kind = (md.get("kind") or rec.task.kind or "task").lower()
    path = md.get("path")
    base = _kind_label(kind)
    if path:
        return f"[spare-change] {base} for `{path}`"
    return f"[spare-change] {base} for {rec.task.project_slug}"


def to_issue_markdown(rec: TaskRecord) -> str:
    """Render a TaskRecord as a markdown body suitable for `gh issue create`."""
    if rec.result is None:
        raise ValueError(f"task {rec.task.task_id} has no result yet")
    md = rec.task.metadata or {}
    kind = md.get("kind") or rec.task.kind or "task"
    path = md.get("path")
    cost = rec.result.estimated_cost_usd or 0.0
    duration = ""
    if rec.result.started_at and rec.result.finished_at:
        duration = f"{(rec.result.finished_at - rec.result.started_at).total_seconds():.1f}s"

    intro = (
        "> This issue was generated by [spare-change](https://github.com/apurvrdx1/spare-change), "
        "a system that lets Claude Pro/Max subscribers donate unused weekly credits to open-source "
        "projects. The work below was produced by running Claude against the donor's existing "
        "session — no API spend on your side, no cost to the donor beyond credits that were about "
        "to expire."
    )

    metadata_lines = [
        f"- **Donor:** `{rec.result.agent_id}`",
        f"- **Task kind:** `{kind}`",
        f"- **Project:** `{rec.task.project_slug}`",
    ]
    if path:
        metadata_lines.append(f"- **File:** `{path}`")
    metadata_lines += [
        f"- **Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"- **Duration:** {duration or 'unknown'}",
        f"- **Donor-side cost estimate:** ${cost:.4f} (Anthropic public rates)",
        f"- **Task ID:** `{rec.task.task_id}`",
    ]

    section_header = {
        "review": "## Findings",
        "annotate": "## Suggested annotated file",
        "test-gen": "## Suggested test module",
    }.get(kind, "## Output")

    body = rec.result.output or "(no output)"
    if kind == "annotate" or kind == "test-gen":
        if not body.strip().startswith("```"):
            body = f"```python\n{body}\n```"

    footer = (
        "---\n\n"
        "*Generated by an automated donor-funded review. The donor and spare-change make no "
        "warranty about the accuracy of the suggestions; please review before merging. Bug? "
        "File at https://github.com/apurvrdx1/spare-change/issues.*"
    )

    return "\n".join([
        intro,
        "",
        *metadata_lines,
        "",
        section_header,
        "",
        body.rstrip(),
        "",
        footer,
    ])
